import React from 'react'

export default function Footer() {
  return (
  <div>
  <div className="card">
    <div className="card-header">
      Paint 2023
    </div>
    <div className="card-body">
      <h5 className="card-title">About Us</h5>
      <p className="card-text">Finding the art in neural networks. Our mission is to revolutionise the art world and to become the exclusive provider of art generated by artificial neural networks – paintings which are both unique and exclusive – whereas some try to replicate human behaviour – other take paths of their own. </p>
      
    </div>
  </div>
</div>

  )
}
